development:
  adapter: postgresql
  encoding: unicode
  database: volt_test
  pool: 5
  username: qq
  password: 3751

test:
  adapter: postgresql
  encoding: unicode
  database: volt_test_test
  pool: 5
  username: qq
  password: 3751
